import OpenAI from 'openai';

/**
 * Client-Side Image Hydration Pattern
 * Dynamically queries official Unsplash Search API for each <img> tag after LLM finishes streaming.
 *
 * @param {string} htmlString - Raw HTML document generated by LLM containing transparent image placeholders.
 * @returns {Promise<string>} Updated HTML document with hydrated Unsplash photo URLs.
 */
export async function hydrateImages(htmlString) {
  if (!htmlString || typeof window === 'undefined') return htmlString;

  const apiKey =
    import.meta.env.VITE_UNSPLASH_API_KEY ||
    import.meta.env.VITE_UNSPLASH_ACCESS_KEY ||
    '';

  if (!apiKey) return htmlString;

  try {
    const parser = new DOMParser();
    const doc = parser.parseFromString(htmlString, 'text/html');
    const images = Array.from(doc.querySelectorAll('img'));

    if (images.length === 0) return htmlString;

    const fallbackUrl =
      'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=800&auto=format&fit=crop';

    const fetchPromises = images.map(async (img) => {
      const altText = (img.getAttribute('alt') || img.getAttribute('title') || '').trim();

      if (altText.length > 3) {
        try {
          const res = await fetch(
            `https://api.unsplash.com/search/photos?query=${encodeURIComponent(
              altText
            )}&per_page=1&client_id=${apiKey}`
          );
          if (res.ok) {
            const data = await res.json();
            if (data.results && data.results.length > 0 && data.results[0].urls?.regular) {
              img.setAttribute('src', data.results[0].urls.regular);
              return;
            }
          }
        } catch (err) {
          if (import.meta.env.DEV) console.error('Unsplash hydration error for alt:', altText, err);
        }
      }

      // If fetch fails or no results or alt text <= 3, set generic fallback if src is empty or transparent pixel
      const currentSrc = img.getAttribute('src');
      if (!currentSrc || currentSrc.startsWith('data:image')) {
        img.setAttribute('src', fallbackUrl);
      }
    });

    await Promise.all(fetchPromises);

    const hasDocType = htmlString.toLowerCase().includes('<!doctype html');
    const resultHtml = doc.documentElement.outerHTML;
    return hasDocType ? `<!DOCTYPE html>\n${resultHtml}` : resultHtml;
  } catch (err) {
    if (import.meta.env.DEV) console.error('hydrateImages error:', err);
    return htmlString;
  }
}

/**
 * Clean markdown extraction helper using regex to return ONLY clean HTML
 * starting with <!DOCTYPE html> or <html>.
 */
export function extractHtml(rawResponse) {
  if (!rawResponse) return '';

  // 1. Strip markdown codeblock fences ```html ... ```
  let clean = rawResponse.replace(/```(?:html)?\s*/gi, '').replace(/```$/gi, '').trim();

  // 2. Extract starting from <!DOCTYPE html> or <html...>
  const lower = clean.toLowerCase();
  const docTypeIdx = lower.indexOf('<!doctype html>');
  const htmlIdx = lower.indexOf('<html');

  if (docTypeIdx !== -1) {
    clean = clean.substring(docTypeIdx);
  } else if (htmlIdx !== -1) {
    clean = clean.substring(htmlIdx);
  }

  return clean;
}

/**
 * Safely prepares current HTML context for edit prompts without losing site topic
 */
function compressHtmlForPrompt(html) {
  if (!html) return '';
  let compressed = html
    .replace(/<svg[\s\S]*?<\/svg>/gi, '<svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"/></svg>')
    .replace(/\s+/g, ' ');

  if (compressed.length > 8000) {
    compressed = compressed.slice(0, 8000) + '... (truncated context)';
  }
  return compressed;
}

const SYSTEM_PROMPT = `You are WebCraft AI, an elite web developer creating full, production-ready, highly interactive single-page web applications.

STRICT GENERATION RULES:
1. Output ONLY a valid single-file HTML document starting with <!DOCTYPE html>. Do NOT wrap in markdown fences or include conversational text.

2. IMAGES (CRITICAL RULE):
   - NEVER guess or invent image URLs. Do NOT use Unsplash source links, Pollinations, LoremFlickr, or placeholder image services.
   - For EVERY single <img> tag, you MUST use this exact transparent pixel for the src attribute:
     src="data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs="
   - You MUST write a highly descriptive and specific alt attribute for what the image should depict, based on the section's context.
   - Example Hero: <img src="data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=" alt="modern minimalist luxury living room with white sofa" class="...">
   - Example Product: <img src="data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=" alt="sleek black running shoe side profile" class="...">

3. NO BLOCKING OVERLAYS / EMBEDDED SECTIONS:
   - NEVER create unhidden fixed overlays (like <div class="fixed inset-0">) that block the website screen!
   - Contact forms, reservation forms, and shopping cart drawers MUST be embedded directly inside clean <section> tags in the natural flow of the page (e.g., <section id="contact" class="py-20 rounded-3xl">).
   - Follow the user's requested color scheme and aesthetic (light mode, dark mode, pink/lilac, pastel, gold/vibrant, etc.). Ensure contrast is readable and visually cohesive.

4. SCROLLING & ROOT CONTAINER:
   - The <body> tag MUST be scrollable: class="min-h-screen w-full overflow-y-auto font-sans" (along with your chosen background and text color classes, e.g. bg-slate-950 text-slate-100 for dark mode or bg-slate-50 text-slate-900 / bg-pink-50 text-slate-800 for light/pink mode).
   - NEVER add "h-screen" or "overflow-hidden" to the <body> tag.

5. NAVBAR & EXACT MATCHING SECTION IDs (CRITICAL FOR NAVIGATION):
   - Every single <a> link in the navbar MUST have an href attribute starting with '#' (e.g., href="#menu", href="#about", href="#pricing", href="#contact").
   - You MUST add the EXACT corresponding id attribute to the target section tag (e.g., <section id="menu">, <section id="about">, <section id="pricing">, <section id="contact">).
   - Ensure the id string in <section id="..."> matches the href anchor in <a href="..."> EXACTLY, letter for letter (all lowercase, no trailing words).

6. HEAD CDN REQUIREMENTS:
   - Tailwind CSS: <script src="https://cdn.tailwindcss.com"></script>
   - Lucide Icons: <script src="https://unpkg.com/lucide@latest"></script>
   - Alpine.js: <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script>

7. ALPINE.JS INTERACTIVITY (WORKING TABS & TOGGLES):
   - Interactive category filter tabs or pricing toggles using x-data, @click, and x-show.

8. LUCIDE ICON INITIALIZATION:
   - Place <script>if (window.lucide) lucide.createIcons();</script> before </body>.`;

/**
 * Stream website generation using Gemini or OpenAI-compatible endpoints
 */
export async function streamWebsiteGeneration({ 
  apiKey, 
  baseUrl = 'https://generativelanguage.googleapis.com/v1beta/openai/', 
  model = 'gemini-2.0-flash', 
  prompt, 
  currentCode, 
  onChunk, 
  onError 
}) {
  if (!apiKey) {
    throw new Error("API Key is missing. Please configure your API key in Settings.");
  }

  const client = new OpenAI({
    apiKey: apiKey,
    baseURL: baseUrl || 'https://generativelanguage.googleapis.com/v1beta/openai/',
    dangerouslyAllowBrowser: true
  });

  const messages = [
    { role: 'system', content: SYSTEM_PROMPT }
  ];

  if (currentCode && currentCode.length > 50 && !currentCode.includes('Describe your dream website')) {
    const compressedCode = compressHtmlForPrompt(currentCode);
    messages.push({
      role: 'user',
      content: `Current website HTML:\n\`\`\`html\n${compressedCode}\n\`\`\``
    });
    messages.push({
      role: 'user',
      content: `User requested fix: ${prompt}\n\nPlease output the COMPLETE updated <!DOCTYPE html> document applying this fix while preserving all existing sections, image tags with transparent pixel src="data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=", descriptive alt attributes, matching section IDs, and applying the requested color theme/style changes. DO NOT output conversational text.`
    });
  } else {
    messages.push({
      role: 'user',
      content: `Build a complete, scrollable, multi-section single-page website with embedded sections (NO blocking overlays), Alpine.js tabs, transparent pixel img src tags with descriptive alt attributes, and styled with the user's requested theme/aesthetic for: ${prompt}`
    });
  }

  try {
    const stream = await client.chat.completions.create({
      model: model || 'gemini-2.0-flash',
      messages: messages,
      stream: true,
      temperature: 0.2,
      max_tokens: 8192
    });

    let fullText = '';
    for await (const chunk of stream) {
      const delta = chunk.choices[0]?.delta?.content || '';
      fullText += delta;
      onChunk(fullText);
    }

    return fullText;
  } catch (error) {
    if (import.meta.env.DEV) console.error('AI API Error:', error);
    if (onError) onError(error);
    throw error;
  }
}
